### ISSUE TITLE
?ecostatus cant handle color tags

### ISSUE THREAD

**Issue by Last2Night** [Spoffy/EcoDiscordPlugin#10]
Im using color tags in my server name and this is what DiscordLink prints upon a response to ?ecostatus command. Please either make it able to read color tags or only print the server name we configure in DiscordLink options and ignore the actual server name. Thanks.
![ecostatus](https://user-images.githubusercontent.com/36459795/37462622-3da9ccae-2818-11e8-8382-6fb1332ce3a5.jpg)

**Comment by Spoffy** [comment]
That section is the server description section. If you set the "ServerDescription" parameter in the DiscordLink Config, it should overwrite that section.

![image](https://user-images.githubusercontent.com/4805393/37463974-d2738970-284e-11e8-84ac-255576ea7751.png)

**Comment by Last2Night** [comment]
@Spoffy Thanks.
