### ISSUE TITLE
?ecostatus does not report offline status

### ISSUE THREAD

**Issue by Last2Night** [Spoffy/EcoDiscordPlugin#11]
It seems that the status feature can only report an online status. In case the server is offline the bot simply does not respond to this command. Would be nice if it would actually report the status of the server rather than an online info.
Thanks.

**Comment by Spoffy** [comment]
Unfortunately, it's impossible to do this with the current architecture of the bot - It runs as an Eco plugin, so when the Eco server dies, the bot goes down with it. 

The alternative would be to rewrite the bot and distribute a separate program, which would be significantly more work, as well as more difficult to install!

However, I am considering writing a completely separate bot just for this purpose in the future.
