### ISSUE TITLE
no channel by that name found

### ISSUE THREAD

**Issue by dprince2** [Spoffy/EcoDiscordPlugin#12]
When trying to do a /discordmessage command i get a No channel of that name found, im guessing its the Discord channel, but i have set my default channel, through the steps provided, plus through the server, the server reads the Discord chat just perfectly, 

I am running ECO 7.2.5

Discord link: https://discord.gg/yWBkNZ
Channel trying to access is eco-server-chat
have tried with just channel ECO also.

**Comment by Spoffy** [comment]
/discordmessage is completely independent of the channel linking. The channel linking is done through the configuration page of the server, which /discordmessage is done entirely through in-game commands.

For both, double check your Guild/Server name is set correctly (including capitalization). Feel free to message on Discord if the issue continues!
