### ISSUE TITLE
Why can't I find discord link tab, and my version is 7.3.3.

### ISSUE THREAD

**Issue by bingliCheng** [Spoffy/EcoDiscordPlugin#16]
Why can't I find discord link tab, and my version is 7.3.3....

**Comment by Spoffy** [comment]
My guess is it's not installed correctly. Make sure you've followed the instructions in Installation.md and extracted the ZIP file to the correct folder.

Feel free to attach screenshots of your mods folder and server GUI, as it'll help with Debugging.

**Comment by bingliCheng** [comment]
Does it mean that after installation?

**Comment by Spoffy** [comment]
I'm not sure exactly what you mean, can you clarify? Extracting the ZIP is part of the installation process.

**Comment by bingliCheng** [comment]
I think I know where my problem is...I haven't installed it yet...

**Comment by bingliCheng** [comment]
Colored = bot owner must have 2 Factor Authentication enabled....
I'm already verify, but I can't do it

**Comment by bingliCheng** [comment]
or can u set bot to https://carbonitex.net/discord/bots.. It will be very simple. We just need to pull the bot to our server.

**Comment by Spoffy** [comment]
The bot shouldn't have any permissions that require 2-factor authentication. If that's an issue, I suggest removing those permissions. I'm not exactly sure what the error is you're getting, or how you're getting it. What link are you using to add it to your server?

Unfortunately, it's not possible to add it to carbonitex due to the way the bot is implemented.

**Comment by bingliCheng** [comment]
i dont know really...

**Comment by Spoffy** [comment]
Sorry, there's not much I can do to help then! I suggest going through the installation instructions again from the beginning, redoing everything, and then it might work?

**Comment by bingliCheng** [comment]
I think it's a problem in the discord...

**Comment by bingliCheng** [comment]
Do you want to try my account?..

**Comment by Spoffy** [comment]
All that says is the bot account hasn't been set up correctly yet, or the wrong token has been copied, unfortunately.
