### ISSUE TITLE
DiscordLink crashed the server with following Exception

### ISSUE THREAD

**Issue by Last2Night** [Spoffy/EcoDiscordPlugin#17]
```
--BEGIN DUMP--
Dump Time
04/23/2018 01:03:55

Exception
DSharpPlus.Exceptions.NotFoundException: Not found: 404
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DSharpPlus.Net.DiscordApiClient.<GetGuildMemberAsync>d__63.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DSharpPlus.Entities.DiscordGuild.<GetMemberAsync>d__135.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Eco.Plugins.DiscordLink.DiscordLink.<ForwardMessageToEcoChannel>d__51.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

--END DUMP--
```

**Comment by Spoffy** [comment]
Hey, thanks for the crash dump. I'll look into the cause and patch it in the next release!

On 23 April 2018 00:19:50 BST, Last2Night <notifications@github.com> wrote:
>```
>--BEGIN DUMP--
>Dump Time
>04/23/2018 01:03:55
>
>Exception
>DSharpPlus.Exceptions.NotFoundException: Not found: 404
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>at
>System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
>task)
>at
>DSharpPlus.Net.DiscordApiClient.<GetGuildMemberAsync>d__63.MoveNext()
>--- End of stack trace from previous location where exception was
>thrown ---
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>at
>System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
>task)
>  at DSharpPlus.Entities.DiscordGuild.<GetMemberAsync>d__135.MoveNext()
>--- End of stack trace from previous location where exception was
>thrown ---
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>at
>System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
>task)
>   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>at
>Eco.Plugins.DiscordLink.DiscordLink.<ForwardMessageToEcoChannel>d__51.MoveNext()
>--- End of stack trace from previous location where exception was
>thrown ---
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>at System.Threading.ExecutionContext.RunInternal(ExecutionContext
>executionContext, ContextCallback callback, Object state, Boolean
>preserveSyncCtx)
>at System.Threading.ExecutionContext.Run(ExecutionContext
>executionContext, ContextCallback callback, Object state, Boolean
>preserveSyncCtx)
>at
>System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
>   at System.Threading.ThreadPoolWorkQueue.Dispatch()
>
>--END DUMP--
>```
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Spoffy/EcoDiscordPlugin/issues/17

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Last2Night** [comment]
Had to roll back to 1.1.1 meanwhile as it was crashing our server constantly.

**Comment by Spoffy** [comment]
Dang. I'll patch it first thing tomorrow morning, I need to sleep right now :P

On 23 April 2018 02:57:17 BST, Last2Night <notifications@github.com> wrote:
>Had to roll back to 1.1.1 meanwhile as it was crashing our server
>constantly.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/Spoffy/EcoDiscordPlugin/issues/17#issuecomment-383433268

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by demodude4u** [comment]
@Last2Night Do you by chance have a webhook bot in the same channel?

**Comment by Last2Night** [comment]
@demodude4u I do.

**Comment by Last2Night** [comment]
I rolled back to DiscordLink 1.1.1 which works fine with webhooks

**Comment by Spoffy** [comment]
This should now be fixed. DiscordLink isn't ready for another release yet, but here's a copy that should fix your issue in the meantime.

[DiscordLink_1.1.3_Webhook_Fix.zip](https://github.com/Spoffy/EcoDiscordPlugin/files/1940293/DiscordLink_1.1.3_Webhook_Fix.zip)

**Comment by Last2Night** [comment]
Thank you. I'll give it a shot in a couple if hours.

**Comment by Last2Night** [comment]
@Spoffy Looks like hotfix did the job, no crashes so far. Thanks.

**Comment by Spoffy** [comment]
No problem, glad it sorted it! Thanks for reporting the crash :)
