### ISSUE TITLE
0.7.5 compatibility?

### ISSUE THREAD

**Issue by elfl0rd** [Spoffy/EcoDiscordPlugin#19]
0.7.5 ECO on staging, can you update mod please? :P

**Comment by Spoffy** [comment]
I'll get it sorted tomorrow, Wednesday at the latest! :)

On 18 June 2018 16:44:47 BST, GDragon <notifications@github.com> wrote:
>0.7.5 ECO on staging, can you update mod please? :P
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Spoffy/EcoDiscordPlugin/issues/19

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Spoffy** [comment]
Ended up being trickier than expected to fix. Try version 1.2.2, and let me know if there's any issues.
https://github.com/Spoffy/EcoDiscordPlugin/releases/tag/1.2.2

**Comment by elfl0rd** [comment]
Yes it's work)
But ?trades ignored.

**Comment by Spoffy** [comment]
Can you clarify? If you run ?trades <item> or ?trades <player name> does it work? 

On 20 June 2018 06:06:20 BST, GDragon <notifications@github.com> wrote:
>Yes it's work)
>But ?trades ignored.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/Spoffy/EcoDiscordPlugin/issues/19#issuecomment-398625413

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by elfl0rd** [comment]
![default](https://user-images.githubusercontent.com/4980243/41648302-29c1193a-7481-11e8-8d48-7a63752ae960.png)
Yes, working.
Single command - not.

**Comment by Spoffy** [comment]
Unfortunately, ?trades by itself doesn't list trades. You'll need to specify the name of an item of player. I've added a message that clarifies this to version 1.2.3 (now available).

It's a feature I hope to add in the future when I have more time!
