### ISSUE TITLE
Features request

### ISSUE THREAD

**Issue by Amphysbaenas** [Spoffy/EcoDiscordPlugin#20]
i would like to be able to have on discord:
Login and logout action
property (claim/unclaim)
Sell/buy/tax information
yup it's possible that will spam my discord buyt as i said i need that :)
i will be happy if we can add that information too
Thx for your work spoofy !

**Comment by tuvok81** [comment]
is this possible, that you can add 
- join/parts when a user joined or part the Server?
- changing command Tags from ? to ! or . in a ini file or something
-

**Comment by TheKye** [comment]
If you have the code you should be able to change the prefix

**Comment by Spoffy** [comment]
Hi all - I'll look at putting some of the features @Amphysbaenas suggested in the next major release - I'm looking at redesigning some of the mod internals shortly.

@tuvok81 - I'll make sure changing prefix tag is in the config options in the next release

**Comment by MonzUn** [comment]
@tuvok81 I've implemented support for changing the command tag in settings. It's in a PR right now.

**Comment by MonzUn** [comment]
New issues page at https://github.com/Eco-DiscordLink/EcoDiscordPlugin/issues
