### ISSUE TITLE
login and logout notifications

### ISSUE THREAD

**Issue by devyn242** [Spoffy/EcoDiscordPlugin#21]
I'm trying to modify to allow logins and logouts notifications but i'm having trouble getting the code to compile, I can't work out the networkmanager.getserverinfo() 
no name space
where do I find that I've looked and looked.

if this could be added as an option into the mod it would be great.
glen@devyn.zapto.org
Devyn

**Comment by Spoffy** [comment]
Hi Devyn!
I've helped a couple of people out with this recently - were you one of them? If not, I'll see if I can send a .DLL your way.

**Comment by Spoffy** [comment]
No recent response - assuming solved.
