### ISSUE TITLE
Not working on unix systems?

### ISSUE THREAD

**Issue by LiaraAlis** [Spoffy/EcoDiscordPlugin#22]
Hi together,

first: Big thanks for this plugin!

My server runs under debian with mono.
I've tried to enable this plugin on my server. While starting, there are no errors, the plugin is working and reacts to commands in Eco but the Bot in Discord appears always as offline.
With the same configuration on my local server on Windows 10 it works without problems.

Any ideas?

**Comment by Spoffy** [comment]
Hi LiaraAlis,
I've not tested the plugin on any flavour of Linux, so I'm not sure how well it'll function across the board.
I'd suggest checking your firewall for anything that might be blocking the Discord client. 

Does everything else work, such as text from Eco -> Discord and Discord -> Eco? If so, it might be an issue with the underlying library on Mono.

If not, try setting "Debug" to "true" in the plugin options, and see if there's anything interesting there (feel free to reply with a copy of that log). 

Cheers,
Spoffy

**Comment by LiaraAlis** [comment]
Hi Spoffy,

thanks for your answer.
I updated mono to version 4 (before my mono version was 4.6.2 and the the plugin seems to work now.

If I run into any problems, I'll get back to you.

Regards,
Alexander
