### ISSUE TITLE
Emojis that appear in Eco 

### ISSUE THREAD

**Issue by Conchipedia** [Spoffy/EcoDiscordPlugin#23]
would it be possible to have a list of which Emoji's Appear in Discord rather than trial and Error via Discord side and seeing which ones produce an Emoji and not a **?**

**Comment by Spoffy** [comment]
This is something I can look into - but it's pretty low priority!

**Comment by MonzUn** [comment]
This issue has been moved to https://github.com/Eco-DiscordLink/EcoDiscordPlugin/issues/1
