### ISSUE TITLE
DLLs for Working on the project

### ISSUE THREAD

**Issue by TheKrush** [Spoffy/EcoDiscordPlugin#25]
Could you add to the ReadMe.md how to get the DLLs to be able to contribute to this project? It doesn't contain the Eco dlls required for compilation.

**Comment by TheKye** [comment]
The eco dlls can be found in the server and game files

**Comment by MonzUn** [comment]
> The eco dlls can be found in the server and game files

What exactly do you mean by this? I found a tool for extracting the relevant DLLs, and it gave me all DLLs except Eco.Plugins.dll, so I'm still having the same problem as @TheKrush.
