### ISSUE TITLE
Missing information for configuring manually (without GUI)

### ISSUE THREAD

**Issue by Lokiare** [Spoffy/EcoDiscordPlugin#27]
What files are the configuration options stored in for those of us that don't have access to the server GUI?

**Comment by Spoffy** [comment]
Hi Lokaire,
Here's an example configuration file for you. I'll also make sure there's one included in future releases.
[ConfigExample_1.2.6.zip](https://github.com/Spoffy/EcoDiscordPlugin/files/3044764/ConfigExample_1.2.6.zip)
