### ISSUE TITLE
Discord bot not displaying users/trades etc in chat

### ISSUE THREAD

**Issue by AlexALX** [Spoffy/EcoDiscordPlugin#31]
Hi, i have problem like some people above already reported - bot itself works, i can see messages in game from discord channel, but all commands returning text with empty information like that: 

https://i.imgur.com/rJ17QPTl.png

Also if write in game to connected channel without using /discordmessage command, it still not displayed in discord server.

Server is on linux, maybe thats is problem?

---
Did wrote on https://eco-mods.com/threads/discordlink.80/page-4 but it seems to be inactive.

**Comment by Spoffy** [comment]
Hey Alex!
I'll look into this shortly, must have missed it on eco-mods!

**Comment by AlexALX** [comment]
This issue happens when user disable link preview in discord app, which affects bots content. To solve that - can you make bot mode what will print text as message and not as "attached link" or content.

**Comment by MonzUn** [comment]
The above pull request should solve this issue by converting embeds to plain text if the bot lacks permissions for embed.
