### ISSUE TITLE
Add option for synchronizing Eco and Discord moderators

### ISSUE THREAD

**Issue by MonzUn** [Spoffy/EcoDiscordPlugin#59]
Automatically adding any Discord moderators as Eco server moderators would be a neat quality of life mod.

**Comment by TheKye** [comment]
Maybe set this up so you have to choose a role to associate with for larger communities

**Comment by MonzUn** [comment]
Yeah. My plan was to use the moderator or admin role for Eco and then have the user set a role in Discord.
If I want to go overboard, it would maybe even be possible to fully sync pairs of Eco titles and Discord roles :P

In any case, I want to support syncing only in one direction or both as well as keeping track of who has been set up in this way so that roles can also be revoked in the same way if they are removed from either side.

**Comment by MonzUn** [comment]
This issue has been moved to https://github.com/Eco-DiscordLink/EcoDiscordPlugin/issues/3
