### ISSUE TITLE
Error after updating Link

### ISSUE THREAD

**Issue by ren-kun** [Spoffy/EcoDiscordPlugin#72]
> `[20:55:10.442] [1] [ Info] [Eco] Failed to load server, Exception was Exception: ReflectionTypeLoadException
> Message:Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
> Source:mscorlib
> 
> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
>    at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
>    at System.Reflection.Assembly.GetTypes()
>    at Eco.ModKit.ModKitPlugin.LoadModDlls()
>    at Eco.ModKit.ModKitPlugin.LoadModsData(TaskCompletionSource`1 done)
>    at Eco.ModKit.ModKitPlugin..ctor(TaskCompletionSource`1 done)
>  `

I get this error after I updated the link on my server

**Comment by MonzUn** [comment]
With "updating link" you mean that you updated the version of this plugin and started the server?
Or did this happen when you updated a channel link in the server GUI?

I have a good idea on why this error exists and I will look into fixing it tonight.

**Comment by ren-kun** [comment]
Yes I was previously using 1.2.9 on an ECO server. When I updated it with 2.0 the server would not start due to that error. Removal and rolling back to 1.2.9 resolved the issue..

Good luck with the patch

**Comment by MonzUn** [comment]
Wait, what server version are you running?

I didn't mention this in the release notes (because I'm a dummy and I've been so focused on 9.0) but this version is not backwards compatible with any server version before 0.9.0.

Likewise, the 1.2.9 version is not compatible with version 0.9.0 of the Eco server.

**Comment by ren-kun** [comment]
Ah I see...

Yes Im using pre 0.9 

Thanks for the clarification!

**Comment by MonzUn** [comment]
Sorry for the confusion and thanks for bringing it to my attention!
I have now added a note about this fact in the release notes :)
