### ISSUE TITLE
Add option for syncing Discord Roles and Eco Specialications

### ISSUE THREAD

**Issue by dopeghoti** [Spoffy/EcoDiscordPlugin#78]
If there's any way we can link a person in Discord to a player profile on the Eco server, it's would be really cool to be able to have, say, a `@Lumberjack` role in Discord that automatically  gets assigned to anyone on the server who gets Logging as a specialization.  Is this within the realm of possibility?

**Comment by MonzUn** [comment]
Yes. I'm unsure if I will try to make this for generic roles right away, or if I will go for just admins first though.
It depends on how complicated it gets when I actually delve into the coding of this feature :)

**Comment by MonzUn** [comment]
Moved to https://github.com/Eco-DiscordLink/EcoDiscordPlugin/issues/12
