### ISSUE TITLE
EcoStatus Channel not working

### ISSUE THREAD

**Issue by jcbjoe** [Spoffy/EcoDiscordPlugin#79]
Hello,

I cannot seem to get the eco status working. Does the server need restarting once the details have been added to make this active? 
The channel is verified in the logs and seems to be connected correctly. It has the needed permissions of manage messages and read chat history.

I'm under the impression once this is linked it will automatically add a message it and edit it? Is there something I'm missing

Thanks,
Joe

**Comment by MonzUn** [comment]
Moved to https://github.com/Eco-DiscordLink/EcoDiscordPlugin/issues/14
