### ISSUE TITLE
This platform is not is not web Platform supported

### ISSUE THREAD

**Issue by lefavilla** [Spoffy/EcoDiscordPlugin#8]
We cant start the plugin because eco cmd says "web platform not supported". Idk the cause. Maybe your plugin, because we had no msg like this before the installation. Maybe an eco bug. Maybe an EcoDiscordPlugin bug?

Platform: R2 2012 x64

**Comment by Spoffy** [comment]
Hi lefavilla. Are you running on Windows 7 or earlier by any chance? I've heard that Windows 7 doesn't have the WebSockets library needed to interface with Discord. 

I'm looking into adding support for Windows 7, but I'm not sure when that will happen.

**Comment by lefavilla** [comment]
It is Windows Server R2 2012

**Comment by Spoffy** [comment]
Try making sure you have .NET Framework 4.5 or greater installed. Post here if that doesn't fix the problem :)

**Comment by Spoffy** [comment]
This has been fixed in d3d9a3a, cheers to Jey for doing the legwork. Should work on Windows 7 without issue in the next release.
