### ISSUE TITLE
Unable to launch plugin with server 

### ISSUE THREAD

**Issue by Edgar-BlipparDev** [Spoffy/EcoDiscordPlugin#9]
Extracted zip in Eco Server/Mods as per instruction
Launched server Crashes upon start up: See error log image for more description
![errors](https://user-images.githubusercontent.com/10381947/37351413-e9e004c6-26d2-11e8-94c5-9eb547dc03ef.png)

**Comment by Spoffy** [comment]
Hi Edgar. You'll need to make sure you download the binary release from the "Releases" section. For example, https://github.com/Spoffy/EcoDiscordPlugin/releases/download/1.1.1-7.2.0/DiscordLink_1.1.1_7.2.1.zip .

Let me know if you have any more difficulties!
